
:toc:
:toc-placement!:

= EQ/R Anaconda Packages

toc::[]

== Quickstart

* Use `PLATFORM/conda-platform.sh` to build the Conda package.
** This always does `conda build purge-all`, which is necessary
* Use `conda-install.sh` to install the Conda package
** This installs the deps separately

== End user interface

The users should be able to simply do:

----
$ conda install -c conda-forge -c swift-t eq-r
----

== Supported platforms

These are standard directory names:

* `linux-64`:  "Linux on PC":  Works
* `osx-64`:    "Mac on PC":    Works
* `osx-arm64`: "Mac on ARM":   WIP
+
This plaform skips Ant, the C compiler, and ZSH, and assumes they are on the user system:
* `aarch64`:   "Linux on ARM": WIP

Python version 3.11 is supported.
WIP: 3.8, 3.9, 3.10 .

== Definitions

PKG::
The package generated by `conda build`

CONDA::
The maintainer's Conda installation/environment used to build the PKG

RECIPE_DIR::
One such directory per platform, e.g., `/path/to/EQ-R/conda/linux-64` +
This is set in the environment at build time by Conda.

LOG::
The output from `build-generic.sh`.  Should be in `RECIPE_DIR`.

== Script architecture

. Each `RECIPE_DIR` directory has a `conda-platform.sh` script to start the build.
. This calls the top-level `conda-build.sh` script.
. `conda-build.sh` calls back to `RECIPE_DIR/deps.sh` to set up platform-specific dependencies
. This sets up `meta.yaml` for the `RECIPE_DIR`
. `conda build` calls `build.sh` for the `RECIPE_DIR`, but this simply
  calls the reusable `build-generic.sh` at the top level.

When testing an installation:
* `conda-install.sh` also accesses `RECIPE_DIR/deps.sh` for platform-specific dependencies (see "Maintainer workflow")
* User installation automatically handles dependencies

== Maintainer workflow

Setup:

* Run `setup-conda.sh` to setup a working Conda environment
* Run the Swift/T `dev/release/make-release-pkg.zsh` script to
  create the "exported" Swift/T source tree in `$TMP/distro`,
  where `$TMP` defaults to `/tmp`.
  This source code location is hard-coded into `meta.yaml`.

Loop:

* Run `conda-platform.sh`.  See notes there.
** Provide `-r` to build with R
* Check `conda-build.log` (`LOG`) for errors.
* Add debug output to `build.sh` as needed to diagnose problems.
* Run `conda-install.sh` to test the installation.  See notes there.

== To create a new platform

* Copy the platform-specific directory
* Run the `conda-platform.sh` script and debug it
* Edit PLATFORM/deps.sh to modify the dependencies as needed

== Anaconda tips

=== Input files

* `meta.yaml`
** Used by `conda build` to find metadata and dependencies
* `build.sh`
** Executed by `conda build` to compile C code, etc.

=== `conda build` behavior

We call `conda build` inside our `conda-build.sh`

. `conda build`
.. Conda creates a temporary environment
.. Installs your packages from `meta.yaml` in that environment
.. Copies `build.sh` to that environment as `conda_build.sh'
.. Runs your `build.sh` script in that environment
.. Bundles the environment
.. Leaves it at: `CONDA/conda-bld/linux-64/swift-t-*.tar.bz2`
. `conda install`
.. Unpacks the bundle
.. Performs path string renaming for libraries and scripts
.. Copies everything into the target Conda environment

=== Speed

It is best to create a Miniconda installation in RAM disk on your system
for building the packages.
Installing Miniconda should take less than 10 seconds.

== Upload to Anaconda

The Anaconda package name is taken from `meta.yaml` and put in the PKG.

----
$ PKG=CONDA/conda-bld/linux-64/swift-t-*.tar.bz2
$ anaconda login
$ anaconda upload $PKG
----

Use `dev/conda/upload.sh` to automate this.

== M4 usage

We use M4 to preprocess `meta.yaml` .

. `meta.yaml` configures the Conda environment,
  so we preprocess this file to:
.. set metadata
.. set environment variables
.. select dependency packages

We restrict our M4 usage to:

* `m4_include()`: does simple file insertion
* `m4_ifelse()`: does conditional substitution +
Syntax: `m4_ifelse(VALUE1, VALUE2, TEXT1)` ⇒ _if (VALUE1 == VALUE2) then insert TEXT1_
* `getenv()`: substitutes in an environment variable value

See `dev/conda/common.m4` for `getenv()` - this is a different script from the `common.m4' for the Turbine submit scripts due to newline requirements.

Example:
----
m4_ifelse(getenv(ENABLE_R),`1',m4_include(pkgs-R.yaml))
----
means: if `$ENABLE_R == 1`, include file `pkgs-R.yaml` here.

== Platform-specific notes

=== osx-64

After end user installation, must update R with:

----
$ conda install -c conda-forge r=4.4
----

For some reason, R is downgraded during the installation.

=== osx-arm64

Weirdness with M4: must insert space between end parenthesis and `m4_dnl` .

Anaconda apparently sets `LDFLAGS` during the build process, see `build-generic.sh` .
